---
name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]

jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: npm install

      - name: Create test build
        run: npm run build

      - name: Execute test cases
        run: npm run test

      - name: Publish on GitHub Pages
        run: npm run publish

      - name: Publush
        run: |
          git config --global user.name 'Imra Kocis'
          git config --global user.email 'imrakocis@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
